name: temp tester
on:
  workflow_dispatch:
    inputs:
      vt:
        type: choice
        description: 'What is the version type (patch, minor major)'     
        required: true
        options: 
        - patch
        - minor
        - major
        default: 'patch'
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
      
    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install ".[build]"
    - name: Bump version
      run: |
          bumpver update --no-fetch --${{ github.event.inputs.vt }}
          echo "ICATCHER_VER=$(bumpver show -n | awk 'END{print $NF}')" >> $GITHUB_ENV
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Version Bump to ${{ env.ICATCHER_VER }}"
          add: "."
