name: Publish iCatcher+
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./src/icatcher/icatcher_app/frontend/
      run: npm ci

    - name: Build
      working-directory: ./src/icatcher/icatcher_app/frontend/
      run: npm run build
    
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
      
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install ".[build]"
    
    - name: Build package
      run: python -m build
    
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}